### ISSUE TITLE
An exception

### ISSUE THREAD

**Issue by HellScre4m** [iTeam-co/Tabchi#4]
Hi. Don't know if I should write persian or not :D
This is the exception I get:
`lua: creator.lua:18: attempt to index a boolean value
stack traceback:
        creator.lua:18: in main chunk
        [C]: ?
`
Can you help?

**Comment by HellScre4m** [comment]
Fixed it by using io.close() instead of :close

**Comment by HellScre4m** [comment]
Ok now I get this:
`
./telegram-cli-1222: /usr/lib/x86_64-linux-gnu/liblua5.2.so.0: no version information available (required by ./telegram-cli-1222)`
`./telegram-cli-1222: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by ./telegram-cli-1222)`
`./telegram-cli-1222: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by ./telegram-cli-1222)
`

**Comment by WebShark025** [comment]
Hi
Run install.sh again
Before that, edit it and remove that '-y' on fourth or fifth line I think.
Then do it all over again

**Comment by HellScre4m** [comment]
It is not solved. I use x86_64 Ubuntu version. I think it gets invalid packages.

**Comment by HellScre4m** [comment]
OK solved the problem. add-apt-repository was not installed on my dist. Please add it to your install script. Thanks

**Comment by HellScre4m** [comment]
I'm sorry but I've got an error via cli each time I sent a command to bot:
` lua: /usr/share/lua/5.2/socket/url.lua:31: bad argument #1 to 'gsub' (string expected, got boolean)`
Can you guide me please?

**Comment by HellScre4m** [comment]
Actually bot doesn't respond to any command, even /echo

**Comment by HellScre4m** [comment]
Investigated redis, changed fullsudo of profiles, nothing changed

**Comment by WebShark025** [comment]
Which branch are you using? master or lastfix?
Because master branch has alot of problems and bugs and I cant fix them (Im not a lua coder. I only support Tabchi where Amir(The actual developer of Tabchi) can not). If you are using that, remove the full /Tabchi directory from your server, then reclone the 'lastfix' branch. It should work
`git pull https://github.com/iTeam-co/Tabchi --branch lastfix`

**Comment by HellScre4m** [comment]
Thanks I will try. Anyway I'm a Java coder. Will be glad if I can help you. I will test lastfix branch and report in this issue

**Comment by WebShark025** [comment]
Oh nice :) I was actually thinking of recoding the whole project in Java, but there is no time :))
Waiting for your response :) Hope it works.

**Comment by HellScre4m** [comment]
OK I tested. Now this problem arises when a command is issued by sudo:
`[Ready] 0>  *** 1485785979.000000 lua: lua-redis.lua:380: redis error: WRONGTYPE Operation against a key holding the wrong kind of value`
Wish your team fixes it soon. Also I have a suggestion for your team to change matching pattern in lua code, to "[http]?[s]?[://]?[t]+[elegram]?[%.me/joinchat/]+.+". This will match new links as well as old ones. Don't know if tg-cli supports new links are not, but I bet your team can edit its source ;)

**Comment by WebShark025** [comment]
Umm, that never happened to me.
Let me check 

--

Also don't worry, it supports t.me links too

**Comment by WebShark025** [comment]
Cant you clean your redis database? cause I think that causes the problem.
The lastfix is working on 4 of my servers running ubuntu 14.04 server, desktop, 16.01 server & 16.10 desktop!

**Comment by HellScre4m** [comment]
Thanks for advice it is fixed now 👍

**Comment by WebShark025** [comment]
Glad to hear that :)
If there were any further problems, I'm at your service :)
Issue closed.
